name: svalbard
dependencies:
  - python>=3.10
  - pip
  - pip:
    - numpy<2.0
    - scipy
    - motor # for async mongoDB
    - fsspec # for general filesystem like data backends
    - gcsfs  # for Google Cloud storage data backend
    - zarr  # for storing array data in the cloud
    - fastapi  # for creating a rest API for the data server
    - uvicorn  # for launching fastapi apps - this may be unneeded right now?
    - httpx  # for async communication with fastapi apps 
    - rustworkx 
    - pydantic # for creating datamodels
    - asteval
    - colorama
    - pandas
    - deprecated
    - build
    - black
    - pytest==8.1.1
    - pytest-cov==4.1.0
    - pylint
    - isort
    - flake8
    - pytest-asyncio==0.23.6 # for testing async modules
    - pylint-pydantic # to make pylint behave with pydantic
    - pre-commit
    - setproctitle
    - orjson # fastapi and orjson are required for measurement executor